obj-$(CPTCFG_WLCORE)			+= wlcore/
obj-$(CPTCFG_WL12XX)			+= wl12xx/
obj-$(CPTCFG_WL1251)			+= wl1251/
obj-$(CPTCFG_WL18XX)			+= wl18xx/

wilink_platform_data-objs	= wilink_platform_data.o
# small builtin driver bit
obj-$(CPTCFG_WILINK_PLATFORM_DATA)	+= wilink_platform_data.o
